# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rule.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import play

class Ui_RuleWindow(object):

    def StartGame(self):
        RuleWindow.hide()
        scores = play.Start()
        user = scores[0]
        computer = scores[1]
        print(user, computer)
        RuleWindow.show()

    def setupUi(self, RuleWindow):
        RuleWindow.setObjectName("Rock Paper Scissor - Rules")
        RuleWindow.setFixedSize(885, 384)
        self.centralwidget = QtWidgets.QWidget(RuleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(-390, -60, 1281, 631))
        self.textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 50, 401, 241))
        self.label.setObjectName("label")
        RuleWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RuleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName("menubar")
        RuleWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RuleWindow)
        self.statusbar.setObjectName("statusbar")
        RuleWindow.setStatusBar(self.statusbar)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 30, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.retranslateUi(RuleWindow)
        QtCore.QMetaObject.connectSlotsByName(RuleWindow)

    def retranslateUi(self, RuleWindow):
        _translate = QtCore.QCoreApplication.translate
        RuleWindow.setWindowTitle(_translate("RuleWindow", "RuleWindow"))
        self.textBrowser.setHtml(_translate("RuleWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\"wp8121942.png\" /></p></body></html>"))
        self.label.setText(_translate("RuleWindow", "<html><head/>\n"
"<body><ul><li><p><span style=\" font-size:14pt;\">Allow use of webcam to collect images</span></p></li><li><p><span style=\" font-size:14pt;\">Use three actions : rock, paper, scissors</span></p></li><li><p><span style=\" font-size:14pt;\">Use a plain background</span></p></li><li><p><span style=\" font-size:14pt;\">Rock crushes Scissors</span></p></li><li><p><span style=\" font-size:14pt;\">Scissors cuts Paper</span></p></li><li><p><span style=\" font-size:14pt;\">Paper covers Rock</span></p></li></ul></body></html>"))
#import rules_rc
        self.pushButton_2.setText(_translate("RuleWindow", "Start"))
        self.pushButton_2.clicked.connect(self.StartGame)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RuleWindow = QtWidgets.QRuleWindow()
    ui = Ui_RuleWindow()
    ui.setupUi(RuleWindow)
    RuleWindow.show()
    sys.exit(app.exec_())
